name: build test

on:
  push:
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    name: build in native linux
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: install dev dependencies
        run: |
          sudo apt-fast -qq update -y
          sudo apt-fast -qq install -y libva-dev libvdpau-dev libnuma-dev ninja-build libtool
          sudo -EH pip3 install meson

      - name: build ffmpeg
        run: |
          while sleep 300; do echo "=====[ $SECONDS seconds still running ]====="; done &
          SKIPINSTALL=yes VERBOSE=yes NUMJOBS=4 ./build-ffmpeg --build --enable-gpl-and-non-free
          kill %1
      - name: check shared library
        run: |
          ldd ./workspace/bin/ffmpeg
      - name: test run ffmepg
        run: |
          ./workspace/bin/ffmpeg -hide_banner -decoders
          ./workspace/bin/ffmpeg -hide_banner -encoders
          ./workspace/bin/ffmpeg -buildconf
      - name: clean up
        run: |
          ./build-ffmpeg --cleanup

  build-macos:
    name: build in native macOS
    runs-on: macos-10.15
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: install dev dependencies
        run: |
          brew install -q bash ninja make cmake automake libtool mercurial
          pip3 install meson
      - name: build ffmpeg
        run: |
          while sleep 300; do echo "=====[ $SECONDS seconds still running ]====="; done &
          SKIPINSTALL=yes VERBOSE=yes ./build-ffmpeg --build --enable-gpl-and-non-free
          kill %1
      - name: check shared library
        run: |
          otool -L ./workspace/bin/ffmpeg
      - name: test run ffmepg
        run: |
          ./workspace/bin/ffmpeg -hide_banner -decoders
          ./workspace/bin/ffmpeg -hide_banner -encoders
          ./workspace/bin/ffmpeg -buildconf
      - name: clean up
        run: |
          ./build-ffmpeg --cleanup

  build-docker:
    name: build in docker
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: pull base image
        id: ubuntu_pull
        run: |
          docker pull ubuntu:20.04
      - name: run if ubuntu_pull failed
        if: failure() && steps.ubuntu_pull.outcome == 'failure'
        run: |
          docker pull ubuntu:20.04
      - name: build ffmpeg
        run: |
          docker build -t ffmpeg:ubuntu -f Dockerfile .
      - name: test run ffmepg
        run: |
          docker run --rm ffmpeg:ubuntu -hide_banner -decoders
          docker run --rm ffmpeg:ubuntu -hide_banner -encoders
          docker run --rm ffmpeg:ubuntu -buildconf

  build-cuda-ubuntu-docker:
    name: build in ubuntu docker with cuda
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: pull base image
        id: cuda_ubuntu_pull
        run: |
          docker pull nvidia/cuda:11.1-devel-ubuntu20.04
          docker pull ubuntu:20.04
      - name: run if cuda_ubuntu_pull failed
        if: failure() && steps.cuda_ubuntu_pull.outcome == 'failure'
        run: |
          docker pull nvidia/cuda:11.1-devel-ubuntu20.04
          docker pull ubuntu:20.04
      - name: build ffmpeg
        run: |
          docker build -t ffmpeg:cuda-ubuntu -f cuda-ubuntu.dockerfile .
      - name: test run ffmepg
        run: |
          docker run --rm ffmpeg:cuda-ubuntu -hide_banner -decoders
          docker run --rm ffmpeg:cuda-ubuntu -hide_banner -encoders
          docker run --rm ffmpeg:cuda-ubuntu -buildconf

  build-cuda-centos-docker:
    name: build in centos docker with cuda
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: pull base image
        id: cuda_centos_pull
        run: |
          docker pull nvidia/cuda:11.1-devel-centos8
          docker pull centos:8
      - name: run if cuda_centos_pull failed
        if: failure() && steps.cuda_centos_pull.outcome == 'failure'
        run: |
          docker pull nvidia/cuda:11.1-devel-centos8
          docker pull centos:8
      - name: build ffmpeg
        run: |
          docker build -t ffmpeg:cuda-centos -f cuda-centos.dockerfile .
      - name: test run ffmepg
        run: |
          docker run --rm ffmpeg:cuda-centos -hide_banner -decoders
          docker run --rm ffmpeg:cuda-centos -hide_banner -encoders
          docker run --rm ffmpeg:cuda-centos -buildconf

  build-full-static:
    name: full static build in docker
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: pull base image
        id: cuda_ubuntu_pull
        run: |
          docker pull nvidia/cuda:11.1-devel-ubuntu20.04
      - name: run if cuda_ubuntu_pull failed
        if: failure() && steps.cuda_ubuntu_pull.outcome == 'failure'
        run: |
          docker pull nvidia/cuda:11.1-devel-ubuntu20.04
      - name: build ffmpeg
        run: |
          docker build -t ffmpeg:cuda-static -f full-static.dockerfile .
      - name: test run ffmepg
        run: |
          docker run --rm ffmpeg:cuda-static -hide_banner -decoders
          docker run --rm ffmpeg:cuda-static -hide_banner -encoders
          docker run --rm ffmpeg:cuda-static -buildconf
